<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9ac2f8d4e1026589c88bd46cfe138a3b
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'League\\Flysystem\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'League\\Flysystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9ac2f8d4e1026589c88bd46cfe138a3b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9ac2f8d4e1026589c88bd46cfe138a3b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
